# Для добавления стадии ввести 'state' и соответсвую цифру по списку
# перед каждым предложений в каждой стадии ставить тире и пробел
# Например:
# state9:
#   - приветка
#   - че делаешь

state1:
    - state1


state2:
    - state2


state3:
    - state3


state4:
    - state4


state5:
    - state5


state6:
    - state6


state7:
    - state7


state8:
    - state8

