# Текущая версия бота
version: 2.5.0.1

# Логирование
text_handler_controller:
    accept_handling: true
    accept_interface: false
    accept_logging: true
    accept_printing: true
    accept_print_property: false


# База данных
db_config:
    username: postgres
    password: postgres
    host: localhost
    port: 5432
    db_name: django_db


# Настройки прокси
proxy:
    - your_proxy_address
    - your_proxy_address



# Настройки токенов
token_config:

    # Токены вк
    vk_tokens:
        - your_vk_token
        - your_vk_token


    # Токен телеграмма
    telegram_token: your_tg_token

    # IDs телеграмма куда отправляются данные
    telegram_id: your_tg_id


# Настройки сообщений
message_config:

    # Блокировка от спама.
    # Количество одновременных сообщений после которых ставиться блокировка
    #   сообщений для пользователя до отправки ему ответа
    block_message_count: 2

    # Задержка сообщения для каждого пользователя в секундах
    delay_response_from: 1
    delay_response_to: 2

    # Время отображния иконки печати
    delay_typing_from: 2  # от
    delay_typing_to: 5    # до

    # Задержка между отправкой сообщений из очереди, 8 это оптимальный вариант.
    # Менять только если начали банить вк или при крайней необходимости
    delay_between_messages_for_account: 8
